// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTask struct {
	UserID string `json:"userId"`
	Task   string `json:"task"`
}

type Task struct {
	ID     int    `json:"id"`
	UserID string `json:"userId"`
	Task   string `json:"task"`
}
