// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTask struct {
	Task   string `json:"task"`
	UserID int    `json:"userId"`
}

type Task struct {
	ID   int    `json:"id"`
	Task string `json:"task"`
	User *User  `json:"user"`
}

func (Task) IsEntity() {}

type User struct {
	ID    int     `json:"id"`
	Tasks []*Task `json:"tasks"`
}

func (User) IsEntity() {}
