// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTaskDto struct {
	Finished bool   `json:"finished"`
	Task     string `json:"task"`
	UserID   int    `json:"userId"`
}

type Task struct {
	ID       int    `json:"id"`
	Finished bool   `json:"finished"`
	Task     string `json:"task"`
	User     *User  `json:"user"`
}

func (Task) IsEntity() {}

type UpdateTaskDto struct {
	ID       int     `json:"id"`
	Finished *bool   `json:"finished"`
	Task     *string `json:"task"`
	UserID   *int    `json:"userId"`
}

type User struct {
	ID    int     `json:"id"`
	Tasks []*Task `json:"tasks"`
}

func (User) IsEntity() {}
